/etc/nging/nginx.conf
```
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 768;
    # multi_accept on;
}

http {
    log_format  logz '$remote_addr - [$time_local] '
                        '"$request" $status ';

    access_log /var/log/nginx/nip.access.log;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;  # Включаем конфигурацию для виртуальных хостов
}
```

Задания

1.конфигурационный файл default сервер и путь до него;
/etc/nginx/sites-enabled/default

2. конфигурационный файл для основного сервера и путь до него;
/etc/nging/nginx.conf

3.список файлов в /etc/nginx/modules-enabled/;
/etc/nginx/modules-enabled/

4.содержимое файла, используемого для basic auth

$ apt install apache2-utils

$ htpasswd -c /etc/nginx/.htpasswd rebrain
Или
openssl
sudo sh -c "echo -n 'sammy:' >> /etc/nginx/htpasswd"
Потом добавить пароль
sudo sh -c "openssl passwd -apr1 >> /etc/nginx/htpasswd"

$ cat /etc/nginx/htpasswd

Картинки
mkdir -p /var/www/rebrain/images/

wget http://rebrainme.com/files/logo_rebrain_black.png

mv logo_rebrain_black.png logo.png